### ISSUE TITLE
ActivePieces app - would be a great addition (has docker compose example available

### ISSUE THREAD

**Issue by petruut** [bigbeartechworld/big-bear-casaos#1178]
https://www.activepieces.com/docs/install/options/docker

**Comment by dragonfire1119** [comment]
Please suggest new apps here: https://community.bigbeartechworld.com/c/big-bear-casaos/bigbearcasaos-suggestions/40

**Comment by petruut** [comment]
> Please suggest new apps here: https://community.bigbeartechworld.com/c/big-bear-casaos/bigbearcasaos-suggestions/40

understood! it's closed as completed, but my CasaOS App Store can't see this...

**Comment by dragonfire1119** [comment]
> https://community.bigbeartechworld.com/c/big-bear-casaos/bigbearcasaos-suggestions/40

Hello, this has not been completed because it was not suggested through the proper channel. https://community.bigbeartechworld.com/c/big-bear-casaos/bigbearcasaos-suggestions/40
