### ISSUE TITLE
Guacamole two factor authenticator 

### ISSUE THREAD

**Issue by fcaronte** [bigbeartechworld/big-bear-casaos#120]
Hi all, i discovered in this day "casa os" and I'm go to try replacing docker+portainer. I install all docker and I noted the guacamole get from your store miss the 2fa authenticator method, I try to understand why and I see the version I was using from here on docker (https://github.com/flcontainers/guacamole) was adding the EXTENSIONS="auth-ldap,auth-duo" during the installation. Is possible to add the extension only after the install or I need to remove your version and install manually?
Maybe consider implementing this extension on your version too.
Thanks a lot :)

**Comment by dragonfire1119** [comment]
Added it! Thanks for the find: https://community.bigbeartechworld.com/t/add-flcontainers-guacamole-to-bigbearcasaos/531?u=dragonfire1119

Next time please post in the BigBearCommunity: https://community.bigbeartechworld.com/c/big-bear-casaos/bigbearcasaos-suggestions/40
