### ISSUE TITLE
Baserow overloading problems

### ISSUE THREAD

**Issue by gymer78** [bigbeartechworld/big-bear-casaos#1302]
Hello!
First of all thank you  for the great job! Together with your apps my Casa OS became a great hub!
I tried to install baserow (both manually like in your youtube video and automatically from your app list) and it didn't go well. In all cases the app icon was on the startview of Casa OS but if I click on it I got "error connection"...
And the most important issue that after installation of baserow my VS was overloaded (processor load about 200%)... Only after I deinstalled baserow, the processor load went down to 2-3%...
Do you have any idea how can I solve this problem?
I have ubuntu 22.04 and casa os 0.4.11

**Comment by dragonfire1119** [comment]
Hello, glad to hear the apps are helping you! For support, please start a forum post here: https://community.bigbeartechworld.com/c/big-bear-casaos/10. Additionally, I would need the logs for the container to assist you further.
