### ISSUE TITLE
New apps

### ISSUE THREAD

**Issue by MaximosPr** [bigbeartechworld/big-bear-casaos#136]
Hey there I've been following your amazing work and it really helps us, not so experienced docker users move forward with casaos. Could you add two more apps to your collection? I need SPIS (simple private image server) and the Minecraft server by itzg? Links are:
https://github.com/gbbirkisson/spis
https://github.com/itzg/docker-minecraft-server

**Comment by dragonfire1119** [comment]
Hello @MaximosPr 

That's awesome that you're following my work. You're welcome, and I'm glad that I'm able to help so many people! My goal is to build a helpful and supportive tech community!

Thanks for the suggestions. Would you be willing to create a separate post for each suggestion you have? It would be really helpful for me to keep track of them that way.

https://community.bigbeartechworld.com/c/big-bear-casaos/bigbearcasaos-suggestions/40 

Do you mind making a post for each one?

**Comment by dragonfire1119** [comment]
Hello @MaximosPr 

That's awesome that you're following my work. You're welcome, and I'm glad that I'm able to help so many people! My goal is to build a helpful and supportive tech community!

Thanks for the suggestions. Would you be willing to create a separate post for each suggestion you have? It would be really helpful for me to keep track of them that way.

https://community.bigbeartechworld.com/c/big-bear-casaos/bigbearcasaos-suggestions/40

**Comment by MaximosPr** [comment]
All right will do!
