### ISSUE TITLE
Immich is unhealthy

### ISSUE THREAD

**Issue by Silaslacasse** [bigbeartechworld/big-bear-casaos#1779]
![image](https://github.com/user-attachments/assets/9f09947b-faaa-44e7-8a35-56ba06ca4248)
Hi, I can't reinstall immich using bigbear image

**Comment by dragonfire1119** [comment]
Hello can you install dozzle and post the output of any errors.

https://youtu.be/lLLNDcHNOuM

You'll need to enable stopped containers in the dozzle settings.

**Comment by Silaslacasse** [comment]
Hi, i installed it, here is the log on immich server : 
![image](https://github.com/user-attachments/assets/f456ab29-8af5-439c-be1c-9fa1248d1599)
look like there is an error with the encoded video
