### ISSUE TITLE
Unable to update Immich to v1.88.x

### ISSUE THREAD

**Issue by gschurck** [bigbeartechworld/big-bear-casaos#18]
My Immich version was v1.87, and when I click on "Check then update" I get this error in CasaOS :
![image](https://github.com/bigbeartechworld/big-bear-casaos/assets/21091232/83988c74-09d0-4e5c-b733-40ee346ae651)
Maybe because the docker-compose structure changed ?

Is there a solution to update it seamlessly through CasaOS ?

**Comment by dragonfire1119** [comment]
Please post any problems or concerns on the following website: https://community.bigbeartechworld.com/. This way, I can stay updated on the issues.

You might also find this thread relevant to your situation: https://community.bigbeartechworld.com/t/update-immich-to-v1-88-1-on-bigbearcasaos/286/2?u=dragonfire1119

**Comment by gschurck** [comment]
Oh okay I didn't know.

**Comment by dragonfire1119** [comment]
> Oh okay I didn't know.

Not a problem at all! I want to express my gratitude for your assistance in keeping Immich current. However, I do have a hectic schedule as I oversee numerous projects, and I'm making an effort to encourage everyone to submit their issues in a single, centralized location, including YouTube comments.
