### ISSUE TITLE
Rocketchat :latest 6.6.0 docker container for CasaOS is broken (infinit reboot of RocketChat in container).

### ISSUE THREAD

**Issue by azzzimut** [bigbeartechworld/big-bear-casaos#185]
Tried to install RocketChat v. 6.6.0 on two different computers (Ubuntu 23.10 and Ubuntu 22.04 LTS).
On both PCs the behavor of container is similar: in docker image the RocketChat process loads RAM from 150 mb up to mid. 750 mb then stops, restarts and the process repeats. The DB process is fine.

That happens not only with your docker image, but also with image from another repositary: https://github.com/WisdomSky/CasaOS-Coolstore/tree/main/Apps/rocket-chat 

Please try it yourself, I think something is broken.

**Comment by azzzimut** [comment]
I forgot to mention that in previous versions of RocketChat I wasn't able to spot this problem.

**Comment by dragonfire1119** [comment]
Thanks for letting me know. I have downgraded the Rocket.Chat version to 6.5.3 for now. There seem to be some issues with 6.6.0.
