### ISSUE TITLE
Any chance you guys could add Tube Archivist?

### ISSUE THREAD

**Issue by petruut** [bigbeartechworld/big-bear-casaos#213]
https://www.tubearchivist.com

I'm sure this would be super easy for many of you, since the documentation seems good on the repository - it'd be great to have a quickly deployable, pre-configured instance.

**Comment by dragonfire1119** [comment]
This doesn't look like it would be a good thing to add, and this looks like it could go against YouTube TOS, which we would not support.

https://community.bigbeartechworld.com/t/big-bear-tech-world-youtube-channel-policy/826?u=dragonfire1119

Thanks for the suggestion feel free to suggest more ideas on: https://community.bigbeartechworld.com/c/bigbearyoutube/bbyt-suggestions/7
