### ISSUE TITLE
Kasm - Container for service "db" is unhealthy

### ISSUE THREAD

**Issue by dpalusak** [bigbeartechworld/big-bear-casaos#232]
I have installed Kasm using BigBearCasaOs docker compose file and getting the following error when trying to install any app (this specifically is VS Code).  Kasm installs successfully and I can see the web UI but when I try to install any app I get this error.  Not sure if you have seen this or not yet but I cannot get past it.

**Comment by dragonfire1119** [comment]
I would need more information on this. Can you check the logs?

You can install Dozzle.

https://youtu.be/lLLNDcHNOuM

**Comment by dpalusak** [comment]
Christopher,
I have installed Dozzle.  Is there anything specific you would like from there?  I have attached the logs from the container.  Just a question, have you installed full Kasm app and tried to install an app and see the same behavior?
[Kasm Logs.txt](https://github.com/bigbeartechworld/big-bear-casaos/files/14461014/Kasm.Logs.txt)

**Comment by dpalusak** [comment]
I go to my CasaOS dashboard
I filter for BigBearCasaOS and I scroll to Kasm
I click install
I change the port to something else because 3000 is already used (in this case I chose 4000)
Once the install is complete, I go to the https://IPaddress:4000
It asks me to accept the Kasm EULA
It then asks for a password for admin and user
Then I can pick which apps I want to install
I pick one (say Chrome) and click install
It pulls down the image then I get the error attached
![Screenshot 2024-03-20 at 2 14 21 PM](https://github.com/bigbeartechworld/big-bear-casaos/assets/17187554/92643784-c086-4cf3-bdca-f492c5da7691)
