### ISSUE TITLE
Cannot change Upload size?  Help

### ISSUE THREAD

**Issue by SHR1SHAK** [bigbeartechworld/big-bear-casaos#235]
Checking out WordPress and found this, tried and it worked with no problem but cannot figure out how to increase the upload size in WordPress. I mainly use cpanel and could not find any .htaccess or php.ini files that I can change to increase the upload size. Please Guide me

**Comment by dragonfire1119** [comment]
Thank you for reaching out. For official community support, please visit our forum at: https://community.bigbeartechworld.com/c/big-bear-casaos/10. We encourage you to start a new post there, where our community can assist you further. We appreciate your understanding.
