### ISSUE TITLE
How to use the webcam on octoprint

### ISSUE THREAD

**Issue by InfinixBlade** [bigbeartechworld/big-bear-casaos#240]
Im trying to use octoprint but i cannot get the webcam to run. Im using ubuntu server latest stable to run casaos.

**Comment by dragonfire1119** [comment]
Thank you for reaching out. For official community support, please visit our forum at: https://community.bigbeartechworld.com/c/big-bear-casaos/10. We encourage you to start a new post there, where our community can assist you further. We appreciate your understanding.
