### ISSUE TITLE
update ROMM image to 3.7.0-alpha.1

### ISSUE THREAD

**Issue by HazelMoon** [bigbeartechworld/big-bear-casaos#2405]
so EmulatorJS has been updated and so the web emulator shows outdated and doesn't allow you to play

![image](https://github.com/user-attachments/assets/b00185be-1887-4590-bb70-b9ad0fb77bda)

**Comment by dragonfire1119** [comment]
This has been fixed: https://community.bigbeartechworld.com/t/need-to-update-romm-to-alpha-rommapp-romm-3-7-0-alpha-1/2369/3?u=dragonfire1119
