### ISSUE TITLE
Focalboard can't move data out of /DATA directory

### ISSUE THREAD

**Issue by KalebSchmidlkofer** [bigbeartechworld/big-bear-casaos#300]
I'm trying to move focalboard's data dir from /DATA/AppData/big-bear-focalboard/data to /media/ssd/focalboard/data but I keep getting an error thats saying stuff like "can't write to readonly db"

**Comment by dragonfire1119** [comment]
Thank you for reaching out. For official community support, please visit our forum at: https://community.bigbeartechworld.com/c/big-bear-casaos/10. We encourage you to start a new post there, where our community can assist you further. We appreciate your understanding.
