### ISSUE TITLE
What is your planning regarding Immich updates?

### ISSUE THREAD

**Issue by AndreaDiNapoli** [bigbeartechworld/big-bear-casaos#4]
Hi and thank you for your awesome CasaOS list!
I was wondering what is your plan about current and future update of the Immich app.

The developers update the server and apps regularly and explicitly say it should be keeped up-to-date server-wise in order to not have incompatibility. That's why I am asking.

**Comment by dragonfire1119** [comment]
I plan on keeping it up-to-date. I am extremely busy, so I do depend on the community to let me know, or somebody can start a pull request to help out.

You can join the BigBearCommunity to let me know of things: https://bit.ly/bbtw-community

**Comment by dragonfire1119** [comment]
Immich has been updated: https://github.com/bigbeartechworld/big-bear-casaos/commit/305cc1ee747e837a691a7198021559efa0bd042c

Thank you for letting me know.

**Comment by AndreaDiNapoli** [comment]
Thank you for answering so swiftly!
It wasn't my intention to pretend or complain, of course! 

Thank you for updating! I will definitely look out to the community!

**Comment by dragonfire1119** [comment]
@AndreaDiNapoli I didn't take it as you were complaining; you had a genuine concern. I will try my best to keep things up to date :)

**Comment by AndreaDiNapoli** [comment]
Hi @dragonfire1119!
I just wanted to advise you that the new Immich update need some special care in order to be made, in case you may have missed that!

You can see the blog about it here: [https://github.com/immich-app/immich/discussions/5086](url)

:)

**Comment by dragonfire1119** [comment]
> Hi @dragonfire1119! I just wanted to advise you that the new Immich update need some special care in order to be made, in case you may have missed that!
> 
> You can see the blog about it here: [https://github.com/immich-app/immich/discussions/5086](url)
> 
> :)

Thank you, yes, I've been told: https://github.com/bigbeartechworld/big-bear-casaos/pull/12#issue-2000404677.

Remember to post for issues or updates on: https://community.bigbeartechworld.com/
