### ISSUE TITLE
Cannot scrape recipes with URL on fresh install of Mealie Big Bear

### ISSUE THREAD

**Issue by dino9848** [bigbeartechworld/big-bear-casaos#411]
I installed Mealie with Big Bear on CasaOS and initially was able to scrape recipes.  Had some errors in the initial few recipes and user accounts created so started over with a fresh install with delete of user data.  After reinstall of current version available, unable to scrape recipes.  Works fine when I use the demo on mealie.io web page, the scraper works fine.

**Comment by dragonfire1119** [comment]
Hello, please move this issue to https://community.bigbeartechworld.com/ so I can keep up with everything and it might help people in the future.
