### ISSUE TITLE
immich server  doesn't find DB

### ISSUE THREAD

**Issue by jeremyit** [bigbeartechworld/big-bear-casaos#414]
hi,
Immich doesn't work for me, logs in server container and microservices  :

``
Error: getaddrinfo ENOTFOUND immich-redis
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'immich-redis'
}
Error: getaddrinfo ENOTFOUND immich-postgres
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)
[Nest] 7  - 04/22/2024, 10:29:40 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (3)...

**Comment by dragonfire1119** [comment]
Hello, please move this issue to https://community.bigbeartechworld.com/ so I can keep up with everything and it might help people in the future.

**Comment by jeremyit** [comment]
Ok sorry, it's done.

**Comment by dragonfire1119** [comment]
> Ok sorry, it's done.

No problem! Thanks for letting me know! I want to know if people are having issues!

Fixed at: https://community.bigbeartechworld.com/t/casaos-immich-server-doesnt-find-db/1137/2?u=dragonfire1119
