### ISSUE TITLE
Add Apps Request

### ISSUE THREAD

**Issue by Doocter** [bigbeartechworld/big-bear-casaos#439]
Server of VPNhook:
https://github.com/vpnhood/VpnHood/releases/
[VpnHoodServer.docker.yml]

Server for Simplex Chat
https://github.com/simplex-chat/simplexmq?tab=readme-ov-file#install-binaries

**Comment by dragonfire1119** [comment]
Thank you for the suggestion! Please post the suggestions here. https://community.bigbeartechworld.com/c/big-bear-casaos/bigbearcasaos-suggestions/40 One suggestion per post.
