### ISSUE TITLE
Support for Obsidian LiveSync.

### ISSUE THREAD

**Issue by kaumudpa** [bigbeartechworld/big-bear-casaos#6]
Hi, 

I have been following your YT channel for some time now and wanted to thank you for this repo.

Can you look at this repo - `https://github.com/vrtmrz/self-hosted-livesync-server` 
Its basically a selfhosted Obsidian LiveSync Server. Adding this to our repo would be amazing.

I would also suggest you to look at[ TIPI HomeServer Management](https://www.runtipi.io/) its similar to CasaOS but have some apps which are more complex and adding these apps to your repo would be an excellent increment.

**Comment by dragonfire1119** [comment]
I truly appreciate your message and for being a part of the BigBearCommunity! It's fantastic to hear that you've been finding my YouTube content valuable. I'll definitely look at the https://github.com/vrtmrz/self-hosted-livesync-server repository.

Regarding RunTipi, I'm already familiar with it and have created content about it on my channel. I'll certainly review it again to see if any of its apps would make a great addition to my store.

If you happen to have some time, I would greatly appreciate it if you could consider submitting a pull request for https://github.com/vrtmrz/self-hosted-livesync-server. Your contribution would be invaluable to the project.

Once again, thank you for reaching out, and if you have any more recommendations or questions, don't hesitate to get in touch. Your support means a lot!

**Comment by dragonfire1119** [comment]
This has been added: https://community.bigbeartechworld.com/t/added-obsidian-livesync-to-bigbearcasaos/205

**Comment by kaumudpa** [comment]
WOW! Your efforts are appriciated. Thanks Again
