### ISSUE TITLE
Support for RustDesk Server.

### ISSUE THREAD

**Issue by kaumudpa** [bigbeartechworld/big-bear-casaos#72]
Hi, 

Requesting you to look into [RustDesk](https://rustdesk.com/) If we could manage to create an app for its self hosted server - https://github.com/rustdesk/rustdesk-server/blob/master/docker-compose.yml and add it to your App Store.

This server is available on https://github.com/WisdomSky/CasaOS-Coolstore - And hence the suggestion as I know if someone can implement this properly it can only be you.

**Comment by dragonfire1119** [comment]
@kaumudpa Thanks for the suggestion! You can suggest it to be added here: https://community.bigbeartechworld.com/c/big-bear-casaos/bigbearcasaos-suggestions/40
