### ISSUE TITLE
wordpress raspberry pi 4 no matching manifest for linux/arm64/v8 in the manifest list entries

### ISSUE THREAD

**Issue by tweingart89** [bigbeartechworld/big-bear-casaos#728]
Hello,

I have tried to install Wordpress with CasaOS on my raspberry pi 4.
I get the following message:

`no matching manifest for linux/arm64/v8 in the manifest list entries`

![image](https://github.com/bigbeartechworld/big-bear-casaos/assets/73897044/da05312f-e6de-4656-ad88-67dbe04061fb)

Is there a way to make this work?
thanks

**Comment by dragonfire1119** [comment]
To keep things organized, please start a forum post on BigBearCommunity.

https://community.bigbeartechworld.com/c/big-bear-casaos/10
