### ISSUE TITLE
Photoview support

### ISSUE THREAD

**Issue by jacopeta** [bigbeartechworld/big-bear-casaos#75]
Hi !! is possible to integrate Photoview (https://photoview.github.io/) container support in the store for casaos? i tried to install in casaos as external application but it doesn't work (maybe i cannot do beacuse of my lack of experience). Thank you

**Comment by dragonfire1119** [comment]
@jacopeta thanks for the suggestions. You can suggest it to be added here: https://community.bigbeartechworld.com/c/big-bear-casaos/bigbearcasaos-suggestions/40
