### ISSUE TITLE
RomM docker image changed

### ISSUE THREAD

**Issue by BACONGUDEN** [bigbeartechworld/big-bear-casaos#750]
Changed to https://hub.docker.com/r/rommapp/romm

**Comment by BACONGUDEN** [comment]
Nevermind, seems like CasaOS just had a hickup and downloaded the old image somehow..

**Comment by dragonfire1119** [comment]
> Nevermind, seems like CasaOS just had a hickup and downloaded the old image somehow..

I was going to say it's already up to date. :)
