### ISSUE TITLE
[App Request] KeyCloak

### ISSUE THREAD

**Issue by mjcc30** [bigbeartechworld/big-bear-casaos#791]
Hello, first i want to thank you for all your work !

My request is simple: could you please consider adding KeyCloak as an available identity 
provider in the store?

There is already an open app request (CasaOS-AppStore#126) that has 
been pending for over a year, which suggests there may be interest from the community in 
using KeyCloak.

Single Sign-On (SSO) is becoming increasingly important for security and usability 
reasons. Adding KeyCloak to the store would provide users with an additional option for 
securing their app access.

The link to the open app request is provided below:

[The App Request KeyCloak in CasaOS-AppStore](https://github.com/IceWhaleTech/CasaOS-AppStore/issues/126)

**Comment by dragonfire1119** [comment]
Hello, thanks for the suggestion. Please submit the suggestion here: https://community.bigbeartechworld.com/c/big-bear-casaos/bigbearcasaos-suggestions/40
