### ISSUE TITLE
Dashy No longer working 

### ISSUE THREAD

**Issue by terrorpup** [bigbeartechworld/big-bear-casaos#88]
The current version of Dashy isn't working. It looks like you need to add a line like this 

-v ~/my.conf:/app/public/config.yaml 

I got this from the dashy page for installation. I started dashy on a different machine with the following line 

docker run -d -p 80:4000 -v ~my.conf:/app/public/conf.yml --name dashy --restart=always lissy93/dashy:latest 

That works 

I am not sure how to get that in, unless it's under Environment settings or Container. Without that setting, you only get a midnight blue background.

**Comment by terrorpup** [comment]
This what is showing from the logs when you start it now 

Config file could not be found at ./public/conf.yml

**Comment by dragonfire1119** [comment]
The README specifies the requirement to generate the configuration. I have also developed a script to facilitate this process, which can be found at this link: https://github.com/bigbeartechworld/big-bear-casaos/tree/master/Apps/dashy

For any future inquiries, please direct your questions to: https://community.bigbeartechworld.com/

**Comment by terrorpup** [comment]
Why can't I ask here, I rather not have a thousand logon.  I will do that because I like to get this working with CasaOS, I have it working on my docker swarm, that I am trying to retire.
